### ISSUE TITLE
feat: Support Proxy Server Configuration

### ISSUE THREAD

**Issue by zaki-yama** [kintone/js-sdk#114]
## Motivation

We want to use rest-api-client under the network using proxy server.

NOTE: This feature is available only in Node.js environment.

## Overview

We haven't fixed the interface and need to discuss, but something like the following: The client can accept the proxy server configurations.

```javascript
const client = new KintoneRestAPIClient({
  baseUrl: "https://example.cybozu.com",
  proxy: 'http://our-proxy-server:port',
  // ...
});
```

Or we can respect environment variables such as `HTTP_PROXY` / `HTTPS_PROXY`.

ref. https://github.com/googleapis/google-api-nodejs-client#using-a-proxy

**Comment by shirogani** [comment]
日本語で失礼します。
じぶんページという kintone 連携サービスにて、 `@kintone/rest-api-client` を利用するにあたり、検討を進めております。

> We haven't fixed the interface and need to discuss, but something like the following: The client can accept the proxy server configurations.

旧版の kintone-js-sdk での proxy 設定では、proxy 側の auth についても考慮がありました。
https://github.com/kintone/kintone-js-sdk/blob/master/src/node/connection/Connection.js#L80

私としても auth ありの proxy を使って、 kintone の IP アドレス制限に対応したいと思っておりますので、ご検討いただければと思います！

**Comment by zaki-yama** [comment]
@shirogani 
コメントありがとうございます！
より便利にお使いいただけるよう仕様は適宜見直しながら開発を進めているのですが、

> 私としても auth ありの proxy を使って、 kintone の IP アドレス制限に対応したいと思っております

こういった情報は仕様を決める上で大変参考になります。
ありがとうございます！

Thank you for your comment!
While we're reviewing the specifications so that rest-api-client becomes more convenient, your comment

> 私としても auth ありの proxy を使って、 kintone の IP アドレス制限に対応したいと思っております

really helps us deciding the interface.
We'll take your comment into account. Thank you.
