### ISSUE TITLE
Fix link for help documentation at rest-api-client/README.md

### ISSUE THREAD

**Issue by aotat** [kintone/js-sdk#1198]
## Target Document

packages/rest-api-client/README.md

## Environment

Any browser.
When I clicked \[Client Certificate authentication\], I did not get help documentation.

## Current Behavior

404 Notfound

## Expected Behavior

Get https://jp.cybozu.help/general/en/admin/list_security/list_access/secureaccess.html

**Comment by shintaroNagata** [comment]
@aotat 
Thank you for your PR!
We will deal with it immediately.
