### ISSUE TITLE
Avoid the error caused by cursor limitation after execution of `getAllRecords`

### ISSUE THREAD

**Issue by shintaroNagata** [kintone/js-sdk#1408]
## Package

- @kintone/rest-api-client

## Why

fix https://github.com/kintone/js-sdk-ja/issues/26

## What

In `getAllRecords`, call `DELETE /cursor.json` after fetching records with `cursor.json`.

**Comment by mshrtsr** [comment]
A cursor is deleted automatically when all records are obtained from an existing cursor.

> The maximum valid cursors per domain is 10.
> If this limit is reached, API calls to add new cursors will fail.
> If one of the following actions occur, the number of valid cursors will be reduced:
> - All records are obtained from an existing cursor
> - A valid cursor is deleted
> - A valid cursor expires

https://kintone.dev/en/docs/kintone/rest-api/records/add-cursor/#limitations

`getAllRecords()` fetches all records, so the cursor should have been deleted in a normal case.

If an error is thrown, `getAllRecords()` call delete cursor API in the catch block.
https://github.com/kintone/js-sdk/blob/a4a112bb0ecc5b75d9c89a078aebea14e4c5007f/packages/rest-api-client/src/client/RecordClient.ts#L339
