### ISSUE TITLE
A bug report about uploadFile in kintone/rest-api-client

### ISSUE THREAD

**Issue by h000780** [kintone/js-sdk#1867]
## Target Package

- https://unpkg.com/@kintone/rest-api-client@3.2.2/umd/KintoneRestAPIClient.js

## Environment

- Operating System: MAC OS
- Browser: Chrome

## Current Behavior

I upload the file to kintone through new KintoneRestApiClient().file.uploadFile(file), and then add the returned fileKey to the kintone attachment field,
Check the "Content-Type" of the attachment field in record event.
The "Content-Type" is normal when I upload png or text file
When I upload a pdf or javascript file, the "Content-Type" becomes "application/octet-stream".

We get the js file object through the "onChange" event of <input type="file"></input>, and then upload it to kintone through the "uploadFile" method of kintone-rest-api-client.

## Expected Behavior

When I upload a pdf or javascript file, the "Content-Type" will be same as 'pdf/javascript'

##
 I uploaded file with XMLHttpRequest  and set file type  when convert file to blob object.
The “content-type” in kintone record  was correct.
Maybe we should set file type when convert to blob object in intone-rest-api-client.
Thank you very much!

**Comment by hung-cybo** [comment]
@h000780 

Thanks for your reporting.
We are checking your issue and will reply to you soon.

**Comment by hung-cybo** [comment]
@h000780 

Thank you for your patients.
We decided to fix this issue by supporting auto-detect MIME-type.
You can follow us at https://github.com/kintone/js-sdk/issues/1893

**Comment by hung-cybo** [comment]
@h000780 

This issue is fixed by PR #1893

**Comment by mshrtsr** [comment]
The fixing PR was released in [@kintone/rest-api-client@3.3.0](https://github.com/kintone/js-sdk/releases/tag/%40kintone%2Frest-api-client%403.3.0).
