### ISSUE TITLE
[Feature Request] bump eslint-plugin dependency in dts-gen package

### ISSUE THREAD

**Issue by Lorenzras** [kintone/js-sdk#2177]
### Target Package

@kintone/dts-gen

### Why

V6 comes with a suite of quality-of-life improvements.

### What
Two solutions.

1. [Migration guide for developers-facing changes](https://typescript-eslint.io/blog/announcing-typescript-eslint-v6#developer-facing-changes)
2. Remove eslint dependency altogether.

**Comment by mshrtsr** [comment]
Thank you for your feedback!
We use [@cybozu/eslint-config](https://github.com/cybozu/eslint-config) and it depends on typescript-eslint v5.

I created an issue on @cybozu/eslint-config to continue discussion => https://github.com/cybozu/eslint-config/issues/684.
Please tell your opinion in that issue.

**Comment by mshrtsr** [comment]
@Lorenzras 
Thank you for your feedback!
We use [@cybozu/eslint-config](https://github.com/cybozu/eslint-config) and it depends on typescript-eslint v5.

I created an issue on @cybozu/eslint-config to continue discussion => https://github.com/cybozu/eslint-config/issues/684.
Please tell your opinion in that issue.

**Comment by tasshi-me** [comment]
The latest release of cybozu/eslint-config updated typescript-eslint v5 -> v6.
We will work on updating dts-gen's dependencies.

**Comment by tasshi-me** [comment]
We updated cybozu/eslint-config. The @typescript-eslint/eslint-plugin in deps is now v7.
Thank you for your report.

https://github.com/kintone/js-sdk/blob/62258b20757de22b97cc9a661ffe13ad1e61c7f0/pnpm-lock.yaml#L1976

**Comment by Lorenzras** [comment]
Thanks alot!
