### ISSUE TITLE
[Bug] Encountering TS Errors When Using @kintone/rest-api-client in Vite

### ISSUE THREAD

**Issue by GuSanle** [kintone/js-sdk#2277]
### Summary

In projects built with Vite4, using the @kintone/rest-api-client  results in a TS error. 
This occurs regardless of whether the Vue template or the React template is used.

### Target Package

@kintone/rest-api-client

### Target Version

4.1.0

### Reproduction

1. npm create vite@latest vite-kintone-api 
2. choose react and ts
3. cd vite-kintone-api
4. npm install
5. npm install @kintone/rest-api-client
6. use in main.ts
```ts:
import React from 'react'
import ReactDOM from 'react-dom/client'
import App from './App.tsx'
import './index.css'
import { KintoneRestAPIClient } from "@kintone/rest-api-client";

const client = new KintoneRestAPIClient({
  baseUrl: "https://example.cybozu.com",
  auth: {
    username: import.meta.env.VITE_KINTONE_USERNAME,
    password: import.meta.env.VITE_KINTONE_PASSWORD,
  },
});

ReactDOM.createRoot(document.getElementById('root')!).render(
  <React.StrictMode>
    <App />
  </React.StrictMode>,
)

```
It will show error 
```
Cannot find module '@kintone/rest-api-client' or its corresponding type declarations.ts(2307)
```

### Expected Behavior

No typescript error

### Actual Behavior

It will show typescript error when `import { KintoneRestAPIClient } from "@kintone/rest-api-client";`
```
Cannot find module '@kintone/rest-api-client' or its corresponding type declarations.ts(2307)
```

### Environment

System:
    OS: macOS 13.5.2
    CPU: (10) arm64 Apple M1 Pro
    Memory: 311.53 MB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.5.1 - ~/.nvm/versions/node/v20.5.1/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 9.8.0 - ~/.nvm/versions/node/v20.5.1/bin/npm
  Browsers:
    Chrome: 117.0.5938.88
    Safari: 16.6
  npmPackages:
    @kintone/rest-api-client: ^4.1.0 => 4.1.0 
    typescript: ^5.0.2 => 5.2.2

**Comment by GuSanle** [comment]
online Lint packaging errors check tool:
https://publint.dev/@kintone/rest-api-client@4.1.0

**Comment by mshrtsr** [comment]
@GuSanle 
Thank you for reporting the issue!

We decided to fix this problem.
Please wait for the fix.
If you need a sooner resolution, feel free to create a PR.

**Comment by mshrtsr** [comment]
@GuSanle 
Thank you for your patience.
We released a new rest-api-client version with a fix for this issue (https://github.com/kintone/js-sdk/pull/2334).
Please check the behavior with the latest release.
