### ISSUE TITLE
file.uploadFile で Blob でなく String を指定するとエラーが発生する

### ISSUE THREAD

**Issue by r3-yamauchi** [kintone/js-sdk#231]
https://github.com/kintone/js-sdk/blob/master/packages/rest-api-client/docs/file.md#uploadFile
の Parameters に
file.data	String or Blob	と書かれており、このページの冒頭にも
```
  const FILE = {
    name: "Hello.txt",
    data: "Hello World!"
  };
```
file.data に文字列を指定する例が書かれていますが、
Uncaught (in promise) TypeError: Failed to execute 'append' on 'FormData': parameter 2 is not of type 'Blob'.
が発生します。
```
    const blob = new Blob(["Hello World!"], {
      type: 'text/plain'
    });

    const { fileKey } = await client.file.uploadFile({
      file: {
        name: "Hello.txt",
        data: blob
      }
    });
```
と Blob を指定した場合は問題ありません。

関係のあると思われるソースコード箇所
https://github.com/kintone/js-sdk/blob/master/packages/rest-api-client/src/client/FileClient.ts#L41

kintone-cli を使用して TypeScript で カスタマイズを実装しています。
```
  "dependencies": {
    "@kintone/kintone-ui-component": "^0.6.0",
    "@kintone/rest-api-client": "^1.2.0",
    "react": "^16.8.6",
    "react-dom": "^16.7.0"
  },
  "devDependencies": {
    "local-web-server": "^2.6.1",
    "webpack": "^4.30.0",
    "webpack-cli": "^3.2.3",
    "babel-loader": "^8.0.5",
    "style-loader": "^0.23.1",
    "css-loader": "^2.1.0",
    "core-js": "^3.2.1",
    "regenerator-runtime": "^0.13.3",
    "@babel/core": "^7.3.3",
    "@babel/preset-env": "^7.3.1",
    "@babel/plugin-proposal-class-properties": "^7.3.3",
    "@babel/plugin-syntax-dynamic-import": "^7.2.0",
    "@babel/preset-typescript": "^7.3.3",
    "@babel/preset-react": "^7.0.0",
    "typescript": "^3.6.3",
    "@types/react": "^16.8.16",
    "@types/react-dom": "^16.8.4",
    "@kintone/customize-uploader": "^2.0.5",
    "eslint": "^6.5.1",
    "@cybozu/eslint-config": ">=7.1.0"
  },
```

**Comment by r3-yamauchi** [comment]
エラーを確認した環境
Google Chrome 81.0.4044.138 Windows 10 64bit
Firefox 76.0.1 Windows 10 64bit  `TypeError: FormData.append: Argument 2 is not an object.`
Internet Explorer 11.836.18362.0 Windows 10 64bit

**Comment by zaki-yama** [comment]
@r3-yamauchi 
Thank you for reporting.
We'll investigate it.

**Comment by koba04** [comment]
@r3-yamauchi This has been fixed at #246. We'll release a new version that includes this fix soon. Thank you for you report! 👏👏👏

**Comment by r3-yamauchi** [comment]
Thank you for your responding 🎉🎉

**Comment by koba04** [comment]
@r3-yamauchi We've just released [v1.4.0](https://github.com/kintone/js-sdk/blob/master/packages/rest-api-client/CHANGELOG.md#140-2020-06-02)! Thank you!

**Comment by r3-yamauchi** [comment]
🎉🎉🎉🚀
