### ISSUE TITLE
Feature request: fileUpload supports Stream

### ISSUE THREAD

**Issue by TakashiAihara** [kintone/js-sdk#232]
kintone-js-sdk のように、file.data で Streamを受け取れるようにしていただけると嬉しいです。

**Comment by shisama** [comment]
@TakashiAihara Thank you for your proposal. We will release this as a new feature in a few months.

**Comment by koba04** [comment]
We've added the Stream support in the documentation.
https://github.com/kintone/js-sdk/blob/master/packages/rest-api-client/docs/file.md#parameters
