### ISSUE TITLE
@kintone/rest-api-client Broken Reference Links

### ISSUE THREAD

**Issue by KintoneSteve** [kintone/js-sdk#265]
## Target Package

- @kintone/rest-api-client 1.41

## Environment

- Operating System: MacOS
- Browser: Chrome
- Node.js version: N/A

## Current Behavior

- URL: https://www.npmjs.com/package/@kintone/rest-api-client#references
- The user is receiving a 404 error when clicking any link in the references section: Record, App, File, or Bulk Request.

## Expected Behavior

- URL: https://www.npmjs.com/package/@kintone/rest-api-client#references
- The user is directed to the correct documentation when clicking any link in the references section.

![Screen Shot 2020-06-15 at 10 03 28 AM](https://user-images.githubusercontent.com/50394346/84686346-9e555d00-aef0-11ea-8ca7-cfbe0110a8e7.png)
![Screen Shot 2020-06-15 at 10 05 45 AM](https://user-images.githubusercontent.com/50394346/84686352-a01f2080-aef0-11ea-9d8d-113b07e7f14b.png)

**Comment by koba04** [comment]
@KintoneSteve 
Thank you for reporting!
We'll fix it soon and publish a new version to update the page of the npm package.

Until we fix this, please refer to the GitHub page directly instead of the npm package page.
https://github.com/kintone/js-sdk/tree/master/packages/rest-api-client

**Comment by shisama** [comment]
@KintoneSteve 
Fixed broken links and published to npmjs.com. So we close this issue.
https://www.npmjs.com/package/@kintone/rest-api-client#references
