### ISSUE TITLE
Feature request: OAuth access token authorization

### ISSUE THREAD

**Issue by r3-yamauchi** [kintone/js-sdk#64]
I need support for OAuth access token authorization feature.
https://developer.kintone.io/hc/en-us/articles/360001562353/

setting the access token in the **Authorization: Bearer** header.

This feature has been waiting for a long time ago.
https://github.com/kintone/kintone-basejs-sdk/pull/65
https://github.com/kintone/kintone-js-sdk/issues/32

**Comment by zaki-yama** [comment]
@r3-yamauchi 
Thank you for your feedback!
We're planning to support this header in the future release.

**Comment by koba04** [comment]
@r3-yamauchi 
We've just added a support OAuth access token as #149 . 
We'll release a new version that includes this in a few weeks.
Thank you for reporting this!

**Comment by r3-yamauchi** [comment]
対応ありがとうございます！

**Comment by zaki-yama** [comment]
@r3-yamauchi 
We released this feature in [v1.2.0](https://www.npmjs.com/package/@kintone/rest-api-client/v/1.2.0) .
