### ISSUE TITLE
BulkRequest する際に buildPathWithGuestSpaceId を使いたい

### ISSUE THREAD

**Issue by r3-yamauchi** [kintone/js-sdk#79]
BulkRequest のパラメータ requests[].api で APIのパスを指定する際に必要になるため
buildPathWithGuestSpaceId メソッドを public に使えるようにして欲しい。

※ buildPathWithGuestSpaceId メソッドが public でないため独自実装している例
https://github.com/r3-yamauchi/kintone-delete-by-cursor/blob/master/src/BulkDel.ts#L48
https://github.com/r3-yamauchi/kintone-delete-by-cursor/blob/master/src/Util.ts#L86

https://github.com/kintone/js-sdk/pull/70/commits/249164cd718fb138ce36572d4a5ec1ca48a97439#diff-0c5d15aae00d4d9c3cb6465b57d756aaR301
のように SDK内で内部的に BulkRequest している場合はよいが、BulkRequest を実行する実装を自分で書く場合もあるため

**Comment by koba04** [comment]
@r3-yamauchi 
フィードバックありがとうございます。
こちら、APIClientにゲストIDが指定されている場合には、apiのpathに自動的にguest idを付与する方法で検討してみようと思います。

Thank you for your feedback!
We'll consider your feature request in the following way.
- Adding a guest ID into an API path in `bulkRequest` automatically if the client has a guest ID.

**Comment by r3-yamauchi** [comment]
@koba04 
ご確認いただきありがとうございます。

> ゲストIDが指定されている場合には、apiのpathに自動的にguest idを付与する

私の感覚では SDKを実際に使う場面として、bulkRequest に渡すパラメータの内容を Postman 等のツールを使い 実際に REST API を実行して確認し、確認したパラメータの内容（各apiのpathはベタ書き）をそのまま jsコードに貼り付けて実行したいケースもあるのではないかと思います。

一方で ゲストスペース／非ゲストスペースアプリのいずれにおいても使われうるツールのようなものを実装する際には

```
      {
        method: "POST",
        api: buildPath("records"),
        payload: {
          app: APP_ID,
```

といったイメージでパラメータを組み立てられると便利です。

いずれの方法でパラメータを指定するか、使用者が選択できると嬉しいです。

**Comment by koba04** [comment]
@r3-yamauchi 
なるほど、ありがとうございます。
現状のAPIClientのI/Fだと、Clientがguest space IDを持つ形になっており、他のAPIに対してもClientがguest space IDを持っている場合は自動的に付与する形になっています。
それに対する一貫性を考えると、guest space IDがClientに渡されている場合には付与する形になるのかなとイメージしていました。
（guest space ID付与するかどうかはClientの生成時に指定する）

**Comment by zaki-yama** [comment]
@r3-yamauchi 
We've just added a new parameter `endpointName` for `bulkRequest()` method ( PR: #152 ).
With this parameter, you can use the same request parameters for both guest space app and non-guest space app.
For more information, please see the doc: 
https://github.com/kintone/js-sdk/blob/master/packages/rest-api-client/docs/bulkRequest.md#parameters

We'll release a new version that includes this in a few weeks.
We really appreciate your feedback!

**Comment by r3-yamauchi** [comment]
ありがとうございます。

requests[].api を指定するか requests[].endpointName で指定するかを選べるということですね。

素晴らしい対応に感謝します。

**Comment by zaki-yama** [comment]
@r3-yamauchi 
ご認識の通りです。
リリースはもう少し先になりますが、使ってみて気になる点があればまたフィードバックいただければ幸いです！

Absolutely.
Since it takes a few more weeks to release this feature, we would appreciate your feedback after its' released.

Thank you.

**Comment by zaki-yama** [comment]
@r3-yamauchi 
We released this feature in [v1.2.0](https://www.npmjs.com/package/@kintone/rest-api-client/v/1.2.0) .
