### ISSUE TITLE
Option "guest-space-id" does not work

### ISSUE THREAD

**Issue by dong0** [kintone/js-sdk#792]
## Target Package

- @kintone/customize-uploader 3.1.9

## Environment

- Operating System: Windows 10
- Browser: 
- Node.js version: v14.16.0

## Current Behavior

Option "guest-space-id" does not work when I use @kintone/customize-uploader to upload JS file to a guest space app.

Preparation: A guest space, and an app in this space

Steps to reproduce:
1. Install @kintone/customize-uploader.
2. Create a JS file.
3. Use command with "guest-space-id" option to upload the JS file to the guest space app.
-> Failed to update customize setting and error occurs
```
E:\github.com\kintone\test>npx kintone-customize-uploader .\dest\customize-manifest.json --guest-space-id 5
? Input your kintone's base URL (https://example.cybozu.com): https://ldong.cybozu.com
? Input your username: test
? Input your password: [hidden]
Start uploading customization files
dest/test.js has been uploaded!
JavaScript/CSS files have been uploaded!
Failed to update customize setting
An error occured, retry
Failed to update customize setting
An error occured, retry
Failed to update customize setting
KintoneRestAPIError: [520] [GAIA_IL23] ゲストスペース内のアプリを操作する場合は、リクエストの送信先を「/k/guest/（ゲストスペースのID）/v1/...」にします。 (TdYjpvnw4Rj5kTL0p4JP)
    at KintoneResponseHandler.handleErrorResponse (E:\github.com\kintone\test\node_modules\@kintone\rest-api-client\lib\KintoneResponseHandler.js:57:15)
    at E:\github.com\kintone\test\node_modules\@kintone\rest-api-client\lib\KintoneResponseHandler.js:35:123
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

#### Note
Maybe problem is here, parameter "guestSpaceId" is missing.
https://github.com/kintone/js-sdk/blob/ea98942fdf103c113d34838e9588caf83cee8400/packages/customize-uploader/src/KintoneApiClient.ts#L49-L56

## Expected Behavior

Can use @kintone/customize-uploader to upload JS file to a guest space app.

**Comment by koba04** [comment]
@dong0 Thank you for reporting this 👍 👍 This has been fixed via #799
