### ISSUE TITLE
Description of return value types in the doc

### ISSUE THREAD

**Issue by mmiyahara** [kintone/js-sdk#827]
## Target Doc

- [js-sdk/packages/rest-api-client/docs/record.md](https://github.com/kintone/js-sdk/blob/master/packages/rest-api-client/docs/record.md)

## Current Behavior

- The return type of `totalCount` is described as `String` even though the value of `totalCount` will be `null` when the request parameter `totalCount` is set to `false` or ignored. I assume that the description should be `String` or `null`.

  - getRecords - Returns
    https://github.com/kintone/js-sdk/blob/master/packages/rest-api-client/docs/record.md#returns-4

- The return type of the `totalCount` is `String` even though the type is described as `Integer` on the reference page. I did not confirm which one is true, but we should fix either of them.

  - createCursor - Returns
    https://github.com/kintone/js-sdk/blob/master/packages/rest-api-client/docs/record.md#returns-18

  - createCursor - Reference
    https://github.com/kintone/js-sdk/blob/master/packages/rest-api-client/docs/record.md#reference-10

**Comment by zaki-yama** [comment]
@mmiyahara 
Thank you for reporting!
We'll investigate it.

**Comment by zaki-yama** [comment]
@mmiyahara 
We checked the behaviors you pointed out.

1)
> The return type of `totalCount` is described as `String` even though the value of `totalCount` will be `null` when the request parameter `totalCount` is set to `false` or ignored. I assume that the description should be `String` or `null`.

In our document, we write

> If the `totalCount` parameter is ignored or is set as `false` in the request, `null` is returned.

in the "Description" column of `totalCount`.
So your point is, it's preferable if we write "String or null" in the **"Type" column**, right?

2)
> The return type of the `totalCount` is `String` even though the type is described as `Integer` on the reference page. I did not confirm which one is true, but we should fix either of them.

Thank you.
There seems to be a typo in the reference page, so we'll fix the reference page side.

**Comment by zaki-yama** [comment]
@mmiyahara 
I added "or `null`" to Type column in the document.
Please see the latest doc: https://github.com/kintone/js-sdk/blob/master/packages/rest-api-client/docs/record.md#returns-4

I really appreciate your feedback! 😄

**Comment by mmiyahara** [comment]
@zaki-yama 
Thank you for checking this issue and sorry for my late response.

> So your point is, it's preferable if we write "String or null" in the "Type" column, right?

You get my point! Thank you for fixing the doc!
