### ISSUE TITLE
RequestBody size of RestApiClient is limited to Axios default maxBodyLength 

### ISSUE THREAD

**Issue by masano** [kintone/js-sdk#915]
## Target Package

- @kintone/rest-api-client@2.0.2

## Environment

- Operating System: macOS Big Sur 11.2.3
- Browser: Google Chrome : 90.0.4430.212（x86_64）
- Node.js version: v14.12.0

## Current Behavior

Recently, You have updated Axios  version to "^0.21.0".
It cause that request body byte size has been limited. 
I think that limited 10MB. it's axios default limit

## Expected Behavior

I think you know solution.
You have wrote note. and useful configuration statement has commentouted.
`// maxBodyLength: Infinity,`
https://github.com/kintone/js-sdk/blob/master/packages/rest-api-client/src/http/AxiosClient.ts#L88-L93

I think that the option parameter is necessary to use  current version Axios.
Or We need A way to set maxBodyLengh parameter.

Please tell me any opinion.

**Comment by zaki-yama** [comment]
@masano 
Thank you for reporting!
You're right! We forgot to uncomment the option 🙇 

We'll fix it in #918 .

**Comment by masano** [comment]
@zaki-yama san

Thank you for your quick fixing!

**Comment by mshrtsr** [comment]
@masano 
This issue was fixed in #918 .
Thank you for the report!

**Comment by zaki-yama** [comment]
We released `@kintone/rest-api-client@2.0.4`.
Please try the latest version.
