### ISSUE TITLE
Enable to create plugins which has a version written in new format

### ISSUE THREAD

**Issue by shintaroNagata** [kintone/js-sdk#971]
## Package

- @kintone/plugin-manifest-validator

## Why

After the Kintone's next update on July 2021, new format version become available like '1.2.3'. 

## What

modify `packages/plugin-manifest-validator/manifest-schema.json` to accept new format.

**Comment by latica-jp** [comment]
Hello,

I'm guessing that the specifications have already been finalized, but I'll try to write down what I hope to do.

It would be nice to be able to write the semver equivalent. For example, `1.2.3-beta.1`.

https://semver.org/lang/ja/

Well, I guess not many people want to write like this... :)

**Comment by shintaroNagata** [comment]
@latica-jp
Thank you for your feedback!
We will use your comment as a reference for future feature additions.
If you don't mind, please tell us the reason that you want to specify the semver equivalent version.

**Comment by latica-jp** [comment]
@shintaroNagata 

Hi, thanks for the reply. Looking forward to future feature additions.

There are cases where we want to include information about builds and releases in the version number, so semver is useful for us as it allows us to include additional information.
